### ISSUE TITLE
Printing from within a function produces empty PDF

### ISSUE THREAD

**Issue by bensutherland** [bensutherland/simple_pop_stats#4]
When saving as a PDF from within a function, particularly for a ggplot object, it seems that this does not properly render and is saved as an empty plot.

**Comment by erondeau** [comment]
Not sure this is still an issue, but:

https://ggplot2.tidyverse.org/reference/print.ggplot.html

"Generally, you do not need to print or plot a ggplot2 plot explicitly: the default top-level print method will do it for you. You will, however, need to call print() explicitly if you want to draw a plot inside a function or for loop."

For example, used to plot Z_scores from rubias in another repository:

```
      pdf(file=paste0(Z_scores.dir,"Z_scores_dist.pdf"))
      
      library(ggplot2)
      
      normo <- tibble(z_score = rnorm(1e06))
      plot_z <- ggplot(Z_scores, aes(x = z_score)) +
          geom_density(colour = "blue") +
          geom_density(data = normo, colour = "black")
      print(plot_z)
      
      dev.off()
```

If there was a specific example from above where this was an issue, let's patch it!

**Comment by erondeau** [comment]
Looks like this was patched in a few places, closing for now.
